version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresdb_container
    environment:
      POSTGRES_DB: spring_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"